### ISSUE TITLE
Colorful Boss Health

### ISSUE THREAD

**Issue by ghost** [PocketEssential/BossBarAPI#6]
How can I make colorful boss health like on example image?  But your plugin is great :). Well made.

**Comment by ghost** [comment]
Try adding § (ALT + 21) and color code!
like §a (green) , §c (red), §9 (blue)

**Comment by ghost** [comment]
But where? I know how to make colorful text but I want to make colorful bar of boss health. It is default pink. How to change the color, for example to green, etc.?

**Comment by uselesswaifu** [comment]
@lolmanz0 that is not possible
