### ISSUE TITLE
Wither? XD

### ISSUE THREAD

**Issue by ghost** [PocketEssential/BossBarAPI#8]
How can I remove this at the end of the world, LOL?
![image](https://cloud.githubusercontent.com/assets/25885263/23334926/a71aa4ca-fba9-11e6-9902-41d54e414611.png)

**Comment by lolmanz0** [comment]
![image](https://cloud.githubusercontent.com/assets/25885263/23678266/b968294a-0383-11e7-882d-ccc3daed6572.png)

**Comment by DelxHQ** [comment]
You cant. in order to show the boss bar, we need to spawn the wither.
